### ISSUE TITLE
Credentials.swift not in repo

### ISSUE THREAD

**Issue by jschmid** [ReSwift/GitHubBrowserExample#1]
The `Credentials.swift` file is not committed in the repo, so the project does not compile.

Could you please provide a sample file?

**Comment by Ben-G** [comment]
Thanks @jschmid for pointing this out! [TIL that I had mistakenly untracked the file instead of just ignoring future updates to it](https://github.com/Ben-G/TIL/blob/master/Tools/git/AssumeUnchanged.md).

Fixed with this commit: 5c79dfa76048c6544d49380ed48d56d61557554c

Let me know if that works for you!

**Comment by jschmid** [comment]
Thanks! It works now.

As a side not, I personally prefer this way to handle it:
- Add "Credentials.swift" in `.gitignore`
- Create a `Credentials.sample.swift` file that has the same content, without the API keys.
- Document in the readme to copy the sample file into the "real" filename.

It has advantages:
- If you change the file content, you can easily commit it again, not like with assume-unchanged
- As a user, when you put your own credentials, you don't see the "real" file as changed, since it is ignored

That's my two cents :+1:
