### ISSUE TITLE
ReSwift question: actionCreatorProvider vs asyncActionCreatorProvider

### ISSUE THREAD

**Issue by AndrewSB** [ReSwift/GitHubBrowserExample#4]
Hey Ben-G,
First of all, thank you for all the great work you've done. Using Redux on iOS Clients is a dream.

I did have a question related to action providers, I am new to Redux so this may be a Redux question, instead of one related directly to ReSwift- 
In your [Github API Request helper](https://github.com/ReSwift/GitHubBrowserExample/blob/master/SwiftFlowGitHubBrowser/APIRequests/GitHubRepositories.swift), you chose to use the `actionCreatorProvider` type signature instead of `asyncActionProvider`? Was that purposeful?

**Comment by Ben-G** [comment]
Hey @AndrewSB,

super sorry, for some reason I missed/forgot about this issue (I'm trying to get better at this: https://twitter.com/benjaminencz/status/746210479832367104).

With the current ReSwift API a `AsyncActionCreator` only needs to be used if you want to dispatch an async action & want a closure to be invoked once the async action completed & updated the state.

Ideally you should never need this functionality, but practically it can simplify things in a few cases. But it is always recommended to listen for updates as a subscriber instead of using this API.

**Comment by Ben-G** [comment]
@AndrewSB For now I'll assume this answered your question and close this issue.

Feel free to re-open if you have any other questions!

**Comment by AndrewSB** [comment]
Hey @Ben-G - sorry for not responding! Yes, your answer makes sense.

Can you let me know what your thoughts on this snippet are? this function uses an asyncActionProvider to make a network request, and then dispatch an action on completion with the result/error: https://github.com/AndrewSB/wrytr/blob/master/wrytr/CreatePostProvider.swift#L21
