### ISSUE TITLE
Issue with Github authentication

### ISSUE THREAD

**Issue by nikolasburk** [ReSwift/GitHubBrowserExample#8]
After hitting the `Authenticate with Github` button, a web view is opened but it navigates only to a 404 page on github.com:

<img width="322" alt="screen shot 2016-07-31 at 13 47 32" src="https://cloud.githubusercontent.com/assets/4058327/17279349/60655b06-5726-11e6-986f-0cedb1f8752b.png">

**Comment by Ben-G** [comment]
I think it isn't obvious since there are no instructions: did you enter a token and a secret into the credentials file? https://github.com/ReSwift/GitHubBrowserExample/blob/master/SwiftFlowGitHubBrowser/GitHubAuth/Credentials.swift

If not, that is the issue. You need to go into your GitHub profile settings and generate an access token.

Let me know if that helped! If it did, I'll add instructions to the repo.

**Comment by michalkalis** [comment]
@Ben-G thanks, you're right, however you also need to set the **Authorization callback URL** to `swiftflowgithub://com.swiftflow.githubbrowser`to your app in the GitHub Settings. And under `gitHubToken` in the `Credentials.swift` you set the **Client ID** and under `gitHubSecret` the **Client Secret** from GitHub.

**Comment by simpzan** [comment]
gitHubToken variable name is misleading, I tried to put `Personal access tokens` there, not working. It should renamed to `githubClientID` to match the one in github settings.

**Comment by Ben-G** [comment]
@michalkalis Thanks for the detailed instructions. These will surely be helpful for others; I'll add them to the README. 

@simpzan You're correct! I'll rename the variables as well, when I update the instructions.

**Comment by Ben-G** [comment]
Hope this is resolved by #8! 

Let me know you're missing anything else and I can re-open. Thanks a lot for the valuable input!
